### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by Khoale1096** [reichlab/reichlab.github.io#103]
Travis-ci.org will be shut down and travis-ci.com will be the only supported platforms starting 01/01/2021 following this [newsletter](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom). Follow this documentation for the migration: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by Khoale1096** [comment]
It seems from the instruction detailed at https://docs.travis-ci.com/user/migrate/open-source-repository-migration we would need the `reichlab` github account to perform the migrating. @nickreich I don't have access to the main `reichlab` account to perform the migration, so should I gain access to the account and do this migration, or having the owner of this account (which I think you have) perform this migration?

**Comment by ydhuang28** [comment]
Travis-ci.org is nearing its end-of-life, and its integration with GitHub is failing; this has prevented me from accessing the configurations of our CI build. I have moved the site CI to GitHub Actions since it is now the dominant CI tool we use in the lab. This issue is now complete!
