### ISSUE TITLE
add alloscore preprint

### ISSUE THREAD

**Issue by nickreich** [reichlab/reichlab.github.io#169]
https://arxiv.org/abs/2312.16201

**Comment by nickreich** [comment]
@mmkerr or @micokoch is this something one of you could add to the website?

**Comment by micokoch** [comment]
Hello. I created a PR with the added publication. Happy new year!

**Comment by micokoch** [comment]
Hi Nick, I updated all preprints and updated and fixed many publications. I guess you can close this issue once you approve.
