### ISSUE TITLE
remove twitter integration

### ISSUE THREAD

**Issue by nickreich** [reichlab/reichlab.github.io#176]

**Comment by micokoch** [comment]
I tried to fix this in [PR#178](https://github.com/reichlab/reichlab.github.io/pull/178) by commenting out some code. It worked when I built it locally, but I'm not sure it was the correct way to fix it.

**Comment by nickreich** [comment]
success! 
<img width="1136" alt="image" src="https://github.com/reichlab/reichlab.github.io/assets/1280767/b4cf23f0-75b5-4172-925c-c7f42e0d12c9">
