### ISSUE TITLE
reclaim twitter space

### ISSUE THREAD

**Issue by nickreich** [reichlab/reichlab.github.io#179]
maybe we could make the "recent news" section a bit wider now that the twitter integration is gone? 

<img width="1136" alt="image" src="https://github.com/reichlab/reichlab.github.io/assets/1280767/088768a7-9bc1-47b1-84b5-b49fb2f04eaf">

**Comment by micokoch** [comment]
Addressed in PR #180 (and I checked that it worked on my local build).

**Comment by micokoch** [comment]
We can close this issue.
