### ISSUE TITLE
add hubverse as a research area on the research page

### ISSUE THREAD

**Issue by nickreich** [reichlab/reichlab.github.io#181]
Would like to add "infrastructure for modeling hubs" as a header on the [research page](https://reichlab.io/research) below infectious disease forecasting with a description (could be lifted/lightly edited from the docs site) and links to the repos.

**Comment by mmkerr** [comment]
Hi @nickreich , I did this under PR#190 but I didn't merge it. Do you want to review it first?

**Comment by nickreich** [comment]
Thanks, @mmkerr, because this is a large change and I can't see what it would look like without merging, I was sort of thinking that maybe we would wait for #175 to be completed and then we could see the preview and merge after that.

**Comment by mmkerr** [comment]
Sounds good!

**Comment by micokoch** [comment]
It seems this issue can be closed?

**Comment by mmkerr** [comment]
Yes, I'll close it. Thanks Alvaro!
