### ISSUE TITLE
add repos associated with papers to research page 

### ISSUE THREAD

**Issue by nickreich** [reichlab/reichlab.github.io#182]
This involves going through repos associated with work that we have done recently and adding those repos to the associated header on the research page. E.g.

 - https://github.com/aaronger/utility-eval-papers could be added to "Infectious disease forecasting"
 - https://github.com/reichlab/covid-hosp-forecasts-with-cases could be added to "Infectious disease forecasting"
 - there are others as well... that could be added based on looking at the publications page and seeing the github repos associated with published papers/preprints...

**Comment by nickreich** [comment]
Let's add https://github.com/reichlab/flusion to the "infectious disease forecasting" label

**Comment by micokoch** [comment]
I added all the GitHub repos I found for papers published 2023-2024 in #216. Before I continued, I wanted to confirm that this looks okay and that you'd like to add them for _all_ papers.

**Comment by micokoch** [comment]
I commented on the wrong issue - sorry! Do you think this issue should be closed? It seems complete?
