### ISSUE TITLE
add github repos associated with papers to the publications page

### ISSUE THREAD

**Issue by nickreich** [reichlab/reichlab.github.io#202]
If repos are added to the publications data, then they will show up as a github link in the publications list. as shown below

<img width="845" alt="image" src="https://github.com/reichlab/reichlab.github.io/assets/1280767/9fd6317c-3127-44fe-b6ae-552e09401bce">

We should add some more, as many are missing.

**Comment by micokoch** [comment]
I added all the GitHub repos I found for papers published 2023-2024 in #216. Before I continue, I want to confirm that this looks okay and that you'd like to add them to all papers.

**Comment by mmkerr** [comment]
Thank you for doing this Alvaro! I had started on this awhile back but I see that you were able to find a lot more repos than I was!

**Comment by micokoch** [comment]
It took me MUCH longer than I expected, but I went through all the papers and added all the GitHub repos. This task is now complete (in #216).

**Comment by nickreich** [comment]
Thank you both for tackling this!
