### ISSUE TITLE
flusion pdf link doesn't work

### ISSUE THREAD

**Issue by nickreich** [reichlab/reichlab.github.io#219]
<img width="277" alt="image" src="https://github.com/user-attachments/assets/bb36db26-e6c3-4ab6-be4a-f010b3289339">

Goes to https://reichlab.io/pdfs/publications/flusion.pdf which doesn't have anything

**Comment by micokoch** [comment]
I learned that if I don't explicitly write a pdf link, the pdf icon still gets built and the link goes to */pdfs/publications/slug.pdf - so, I added explicit links for all publications in #220

**Comment by micokoch** [comment]
This issue can be closed.
