### ISSUE TITLE
add preprint field in metadata for publications, with link item

### ISSUE THREAD

**Issue by nickreich** [reichlab/reichlab.github.io#58]
There are a few papers that have been published, where we'd like to continue to have a link to the preprint. Both as a way of linking to the original work and of highlighting that we submitted a preprint...

**Comment by lepisma** [comment]
Preprints are supported now.

Adding a `preprint` key with a url value in any item in `publications.yml` will show a preprint link in the end as shown:

![image](https://user-images.githubusercontent.com/2487306/35957086-8f3cd81a-0c91-11e8-8c07-d1186af7cbbf.png)

Should it be at a specific place in the order of links? Right now its between the doi group (`article` & `save`) and the `github` link (if present).

**Comment by nickreich** [comment]
great! that placement seems fine to me.

Nick

-- 
Nicholas G. Reich, Ph.D.
Associate Professor
Department of Biostatistics and Epidemiology
School of Public Health and Health Sciences
University of Massachusetts, Amherst

413.545.4534
nick@schoolph.umass.edu
http://reichlab.io/
on twitter: @reichlab
