### ISSUE TITLE
option to link to paper PDF directly

### ISSUE THREAD

**Issue by nickreich** [reichlab/reichlab.github.io#59]
If a PDF of a published paper can be linked to directly through the journal website, having a local copy is either redundant, potentially in violation of copyright, or, if we load up an older version of the paper so it's not in copyright infringement, then it's out of date. 

Could we add an option for a `pdf:` entry in the `.yml` file that, if present with a url, would override the looking for the `slug.pdf` file?

**Comment by lepisma** [comment]
Should be done now (640117b47385130e1071488c5a7f8a7663767972). `pdf` is the field name.
