### ISSUE TITLE
add new preprint to website.

### ISSUE THREAD

**Issue by nickreich** [reichlab/reichlab.github.io#75]
http://biorxiv.org/cgi/content/short/397190v1

**Comment by nickreich** [comment]
@katiehouse3 just nudging on this to make sure it didn't get lost in end of summer shuffle... not super urgent, but would like to get it up on the site soon.

**Comment by katiehouse3** [comment]
Sounds good!
For the paper, do we have the:
- slug
- journal
- volume
- pages
- Github?

Thanks!

**Comment by nickreich** [comment]
So, it's up to you to create the image for the paper (usually I just 
screenshot a square from an image so it looks nice), and that is where 
the slug would be used (for the filename, I think).
journal: bioRxiv
volume: [blank]
pages: [blank]

this paper is a preprint, so the url should be listed as that. GitHub 
repo could be https://github.com/FluSightNetwork/cdc-flusight-ensemble

Let me know if you need more info.
