### ISSUE TITLE
add "previous" and "next" buttons on blog landing page

### ISSUE THREAD

**Issue by nickreich** [reichlab/reichlab.github.io#9]

**Comment by shv38339** [comment]
The buttons for "previous" and "next" have been added but will not be utilized until there are more than 5 posts ("paginate" option may be set in _config.yml to be less than or more than 5 pages).

**Comment by nickreich** [comment]
Can you submit a pull request with the changes?

**Comment by shv38339** [comment]
A pull request...this is different than you pulling the changes that I pushed to my repo? I'll tinker with it...

**Comment by shv38339** [comment]
I believe I correctly submitted a pull request.
